#!/usr/bin/env python3
"""
Generates anim/world3d.json — a solid 3D scene with the camera moving through it.

What it is meant to demonstrate, in one shot:

  * a camera that travels through the space rather than panning across a picture,
    so nearer solids slide across farther ones and you see around them
  * a shared depth buffer, via two spheres that pass through one another
  * smooth shading on the curved primitives against a deliberately flat cube
  * perspective-correct texturing, on the ground plane and on the cube

Written as a generator rather than by hand because the ring of solids is
positional arithmetic, and arithmetic belongs in code — the same reason
build_curves8k.py exists.
"""

import json
import math
import os

W, H = 1920, 1080
CX, CY = W // 2, H // 2
FPS = 60
DUR = 12.0
FOCAL = 1400.0

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def track(*points, ease="cubicinout"):
    """[(t, v), ...] -> the keyframe form the parser expects."""
    out = []
    for i, (t, v) in enumerate(points):
        k = {"t": round(t, 4), "v": round(v, 4)}
        if i > 0:
            k["ease"] = ease
        out.append(k)
    return out


def mesh(oid, shape, x, y, z, size, color, **kw):
    # "z_depth", not "z": the latter is the paint-order integer, and giving a
    # depth there places every solid at the same distance while quietly
    # reordering them.
    o = {
        "id": oid,
        "type": "mesh",
        "shape": shape,
        "x": CX + x,
        "y": CY + y,
        "z_depth": z,
        "anchor": "center",
        "size": size,
        "color": color,
        "ambient": 0.24,
    }
    o.update(kw)
    return o


objects = []

# The ground: a large textured plane, well below the eye. It is what makes the
# camera's travel legible — without a surface to move over, a solid in the void
# reads as if it were the thing rotating.
objects.append(mesh(
    "ground", "plane", 0, 620, 400, 4200, "#8FA3C0",
    texture="../assets/checker.png", ambient=0.55,
))

# A ring of solids around the origin, alternating shape so the smooth ones sit
# next to a flat-shaded cube for comparison.
PALETTE = ["#FF7043", "#42A5F5", "#7EE787", "#FFD166", "#D2A8FF", "#FF6B9D"]
for i in range(6):
    a = 2.0 * math.pi * i / 6.0
    shape = ["torus", "box", "cylinder"][i % 3]
    objects.append(mesh(
        f"ring{i}", shape,
        math.cos(a) * 900.0, 240.0, 500.0 + math.sin(a) * 900.0,
        340, PALETTE[i],
        rotate_y=track((0, 0), (DUR, 360 if i % 2 == 0 else -360), ease="linear"),
        rotate_x=track((0, 12 * i), (DUR, 12 * i + 180), ease="linear"),
    ))

# Two spheres sharing space. Their intersection curve is the depth buffer's
# entire point: without one, whichever is listed last would be drawn whole.
objects.append(mesh("sphereA", "sphere", -150, -60, 400, 620, "#FF7043"))
objects.append(mesh("sphereB", "sphere", 150, -60, 400, 620, "#42A5F5"))

# A textured cube at the centre of the ring, flat-shaded on purpose so its
# facets stay hard next to the smooth spheres.
objects.append(mesh(
    "block", "box", 0, 380, 1500, 460, "#FFFFFF",
    texture="../assets/checker.png", ambient=0.35, smooth=False,
    rotate_y=track((0, 0), (DUR, 180), ease="linear"),
))

# The eye travels an arc of fixed radius about the ring's centre rather than a
# hand-picked list of positions. Distance to the subject then never changes, so
# the framing holds for the whole shot while the viewpoint genuinely moves —
# picking positions by hand gave a pass that ended up inside the spheres.
ORBIT_R = 3000.0
CENTRE = (0.0, 0.0, 500.0)
STEPS = 24

CAMERA = {"perspective": FOCAL}
px, py, pz = [], [], []
for k in range(STEPS + 1):
    f = k / STEPS
    t = f * DUR
    ang = math.radians(-72.0 + 144.0 * f)
    px.append((t, CENTRE[0] + ORBIT_R * math.sin(ang)))
    pz.append((t, CENTRE[2] - ORBIT_R * math.cos(ang)))
    # A rise and fall over the arc: at the top the ring opens out, at the ends
    # the solids line up and occlude one another.
    py.append((t, -320.0 - 620.0 * math.sin(math.pi * f)))

CAMERA["px"] = track(*px, ease="linear")
CAMERA["py"] = track(*py, ease="linear")
CAMERA["pz"] = track(*pz, ease="linear")
CAMERA["tx"] = track((0, CENTRE[0]))
CAMERA["ty"] = track((0, CENTRE[1] + 60))
CAMERA["tz"] = track((0, CENTRE[2]))

scene = {
    "_comment": "A 3D space with the camera moving through it. "
                "Generated by anim/build_world3d.py.",
    "project": {"width": W, "height": H, "fps": FPS, "bg_color": "#070912"},
    "output": {"encoder": "h264_nvenc", "preset": "p6", "cq": 20},
    "scenes": [{
        "id": "world",
        "duration_ms": int(DUR * 1000),
        "camera": CAMERA,
        "objects": objects,
        "timeline": [],
    }],
}

out = os.path.join(HERE, "world3d.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(scene, f, indent=1)
print(f"wrote {out} — {len(objects)} meshes, {DUR:g}s @ {FPS}fps")
